cmake_minimum_required(VERSION 3.21)
file(READ "${CATALOG}" ORIGINAL)
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}")
foreach(CASE header old_id duplicate_mode missing_role)
    if(CASE STREQUAL "header")
        string(REPLACE "entry_id,canonical_role" "vm_node,canonical_role" CONTENT "${ORIGINAL}")
    elseif(CASE STREQUAL "old_id")
        string(REPLACE "ImageAcquisition.Dir," "SrcImageFilesNodeData," CONTENT "${ORIGINAL}")
    elseif(CASE STREQUAL "duplicate_mode")
        string(REPLACE "ImageAcquisition.Dir,ImageAcquisition,acqType,1" "ImageAcquisition.Dir,ImageAcquisition,acqType,0" CONTENT "${ORIGINAL}")
    else()
        string(REPLACE "ImageAcquisition,ImageAcquisition,acqType,0" "Missing,Missing,acqType,0" CONTENT "${ORIGINAL}")
    endif()
    if(CONTENT STREQUAL ORIGINAL)
        message(FATAL_ERROR "Negative fixture ${CASE} did not mutate input")
    endif()
    set(PATH "${TEST_BINARY_DIR}/${CASE}.csv")
    file(WRITE "${PATH}" "${CONTENT}")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DCATALOG=${PATH}" -P "${VERIFIER}" RESULT_VARIABLE RESULT OUTPUT_QUIET ERROR_QUIET)
    if(RESULT EQUAL 0)
        message(FATAL_ERROR "Invalid catalog accepted: ${CASE}")
    endif()
endforeach()
