cmake_minimum_required(VERSION 3.21)
if(NOT DEFINED CATALOG OR NOT EXISTS "${CATALOG}")
    message(FATAL_ERROR "CATALOG must name an existing operator CSV")
endif()
file(STRINGS "${CATALOG}" LINES ENCODING UTF-8)
list(POP_FRONT LINES HEADER)
if(NOT HEADER STREQUAL "entry_id,canonical_role,property,value,display_name,category")
    message(FATAL_ERROR "Invalid operator catalog header")
endif()
list(LENGTH LINES COUNT)
if(NOT COUNT EQUAL 123)
    message(FATAL_ERROR "Expected 123 unique catalog entries, found ${COUNT}")
endif()
set(IDS)
set(ROLES)
set(CONFIGURATIONS)
foreach(LINE IN LISTS LINES)
    string(REPLACE "," ";" FIELDS "${LINE}")
    list(LENGTH FIELDS FIELD_COUNT)
    if(NOT FIELD_COUNT EQUAL 6)
        message(FATAL_ERROR "Catalog entry must have six non-empty fields: ${LINE}")
    endif()
    list(GET FIELDS 0 ID)
    list(GET FIELDS 1 ROLE)
    list(GET FIELDS 2 PROPERTY)
    list(GET FIELDS 3 VALUE)
    list(GET FIELDS 4 LABEL)
    list(GET FIELDS 5 CATEGORY)
    if(ID IN_LIST IDS OR LABEL STREQUAL "" OR CATEGORY STREQUAL "")
        message(FATAL_ERROR "Duplicate ID or empty label/category: ${ID}")
    endif()
    if(ID STREQUAL ROLE)
        list(APPEND ROLES "${ROLE}")
    elseif(NOT ID MATCHES "^${ROLE}[.][A-Za-z][A-Za-z0-9]*$")
        message(FATAL_ERROR "Non-default entry must use Role.Mode ID: ${ID}")
    endif()
    if(NOT PROPERTY STREQUAL "-")
        if(NOT PROPERTY MATCHES "^(mode|acqType)$" OR NOT VALUE MATCHES "^[0-9]+$")
            message(FATAL_ERROR "Invalid mode property/value: ${ID}")
        endif()
    elseif(NOT VALUE STREQUAL "-" OR NOT ID STREQUAL ROLE)
        message(FATAL_ERROR "Missing mode property: ${ID}")
    endif()
    set(KEY "${ROLE}:${PROPERTY}:${VALUE}")
    if(KEY IN_LIST CONFIGURATIONS)
        message(FATAL_ERROR "Duplicate catalog configuration: ${KEY}")
    endif()
    list(APPEND CONFIGURATIONS "${KEY}")
    list(APPEND IDS "${ID}")
endforeach()
list(LENGTH ROLES ROLE_COUNT)
if(NOT ROLE_COUNT EQUAL 39)
    message(FATAL_ERROR "Expected 39 canonical roles")
endif()
foreach(LINE IN LISTS LINES)
    string(REPLACE "," ";" FIELDS "${LINE}")
    list(GET FIELDS 1 ROLE)
    if(NOT ROLE IN_LIST ROLES)
        message(FATAL_ERROR "Unknown canonical role: ${ROLE}")
    endif()
endforeach()
message(STATUS "Catalog valid: 39 canonical roles, 84 non-default presets, 123 distinct configurations")
